# Generated by Django 3.1.5 on 2021-02-03 01:29

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anwsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anwser', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('dislike', models.ManyToManyField(related_name='anwser_dislike', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Quora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, unique=True)),
                ('title2', models.CharField(blank=True, max_length=10000)),
                ('tags', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('General', 'General'), ('Experience', 'Experience'), ('Question', 'Question'), ('Support', 'Support')], default='General', max_length=1000)),
                ('pinned', models.BooleanField(default=False)),
                ('dislike', models.ManyToManyField(blank=True, related_name='Quora_dislikes', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='Quora_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Quora_User', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('dislike', models.ManyToManyField(related_name='comment_dislike', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies_name', to='discuss.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Anwser_comment', to='discuss.anwsers')),
                ('question', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quora_comment', to='discuss.quora')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='anwsers',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quora_anwsers', to='discuss.quora', to_field='title'),
        ),
        migrations.AddField(
            model_name='anwsers',
            name='like',
            field=models.ManyToManyField(related_name='anwser_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anwsers',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Anwser_User', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
